services:
  svelte:
    build:
      context: .
      dockerfile: Dockerfile
    image: tom-website
    container_name: tom-website-dev
    restart: unless-stopped
    ports:
      - "5200:80"
    volumes:
      - .:/app